In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import os

In [2]:
file_path = "data//org//vehicle.dat"
file_name='vehicle'

In [3]:
# 使用read_csv函数加载.dat文件
df = pd.read_csv(file_path, sep=',', header=None) #sep=','
df.iloc[0,:]

0        95
1        48
2        83
3       178
4        72
5        10
6       162
7        42
8        20
9       159
10      176
11      379
12      184
13       70
14        6
15       16
16      187
17      197
18     van 
Name: 0, dtype: object

In [4]:
## usd for .data file
import pandas as pd

# Load the data using a regular expression for any whitespace
df = pd.read_csv(file_path, sep='\s+', header=None)

# Display the first row
df.iloc[0,:]


<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_7936\3254176773.py:5: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(file_path, sep='\s+', header=None)


0      5.000
1      7.000
2     35.000
3      1.400
4      0.400
5      0.657
6      2.330
7     14.000
8     23.000
9      6.000
10     1.000
Name: 0, dtype: float64

In [4]:
df.head(20)

0   1    2    3    4   5    6   7   8    9    10   11   12   13  14  15  \
0    95  48   83  178   72  10  162  42  20  159  176  379  184   70   6  16   
1    91  41   84  141   57   9  149  45  19  143  170  330  158   72   9  14   
2   104  50  106  209   66  10  207  32  23  158  223  635  220   73  14   9   
3    93  41   82  159   63   9  144  46  19  143  160  309  127   63   6  10   
4    85  44   70  205  103  52  149  45  19  144  241  325  188  127   9  11   
5   107  57  106  172   50   6  255  26  28  169  280  957  264   85   5   9   
6    97  43   73  173   65   6  153  42  19  143  176  361  172   66  13   1   
7    90  43   66  157   65   9  137  48  18  146  162  281  164   67   3   3   
8    86  34   62  140   61   7  122  54  17  127  141  223  112   64   2  14   
9    93  44   98  197   62  11  183  36  22  146  202  505  152   64   4  14   
10   86  36   70  143   61   9  133  50  18  130  153  266  127   66   2  10   
11   90  34   66  136   55   6  123  54  17  118  148  224  118   65   5  26   
12   88  46   74  171   68   6  152  43  19  148  180  349  192   71   5  11   
13   89  42   85  144   58  10  152  44  19  144  173  345  161   72   8  13   
14   94  49   79  203   71   5  174  37  21  154  196  465  206   71   6   2   
15   96  55  103  201   65   9  204  32  23  166  227  624  246   74   6   2   
16   89  36   51  109   52   6  118  57  17  129  137  206  125   80   2  14   
17   99  41   77  197   69   6  177  36  21  139  202  485  151   72   4  10   
18  104  54  100  186   61  10  216  31  24  173  225  686  220   74   5  11   
19  101  56  100  215   69  10  208  32  24  169  227  651  223   74   6   5   

     16   17     18  
0   187  197   van   
1   189  199   van   
2   188  196   saab  
3   199  207   van   
4   180  183   bus   
5   181  183   bus   
6   200  204   bus   
7   193  202   van   
8   200  208   van   
9   195  204   saab  
10  194  202   van   
11  196  202   saab  
12  189  195   bus   
13  187  197   van   
14  197  199   bus   
15  186  194   opel  
16  181  185   van   
17  198  199   bus   
18  185  195   saab  
19  186  193   opel

In [18]:
# 对所有含字母的列进行 factorize 编码
for col in df.columns:
    if df[col].dtype == 'object':  # 检查列是否为离散字母
        df[col], _ = pd.factorize(df[col])

print(df)

             0         1       2       3       4         5         6   \
0       28.7967   16.0021  2.6449  0.3918  0.1982   27.7004   22.0110   
1       31.6036   11.7235  2.5185  0.5303  0.3773   26.2722   23.8238   
2      162.0520  136.0310  4.0612  0.0374  0.0187  116.7410  -64.8580   
3       23.8172    9.5728  2.3385  0.6147  0.3922   27.2107   -6.4633   
4       75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277   28.5525   
...         ...       ...     ...     ...     ...       ...       ...   
19015   21.3846   10.9170  2.6161  0.5857  0.3934   15.2618   11.5245   
19016   28.9452    6.7020  2.2672  0.5351  0.2784   37.0816   13.1853   
19017   75.4455   47.5305  3.4483  0.1417  0.0549   -9.3561   41.0562   
19018  120.5135   76.9018  3.9939  0.0944  0.0683    5.8043  -93.5224   
19019  187.1814   53.0014  3.2093  0.2876  0.1539 -167.3125 -168.4558   

            7        8         9   10  
0      -8.2027  40.0920   81.8828   0  
1      -9.9574   6.3609  205.2610   0  
2  

In [5]:
scaler = StandardScaler()

# 对每列数据进行标准化处理
df.iloc[:,:-1] = scaler.fit_transform(df.iloc[:,:-1])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_7132\696250334.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.16058035 -0.32546965  1.25419283 -0.08244465 -1.05454464  1.61873033
  0.40360534 -0.44698215 -0.93303214 -0.08244465 -0.93303214 -0.44698215
 -0.69000714 -0.56849464  0.03906785  0.28209285 -0.56849464  0.64663034
  1.25419283  0.88965534 -1.17605714 -1.17605714  0.03906785 -0.81151964
  0.64663034 -1.05454464 -1.29756964  1.61873033  1.01116784 -1.66210713
 -0.56849464 -0.69000714 -0.08244465  0.88965534 -0.81151964  0.76814284
 -1.41908213 -0.44698215  1.49721783 -1.54059463  0.16058035 -0.69000714
  0.03906785 -0.08244465  3.07688031 -0.08244465 -0.32546965 -1.05454464
 -0.56849464 -0.32546965 -1.90513213 -0.20395715  0.52511784  0.88965534
  0.88965534  0.03906785  0.40360534 -0.56849464  1.61873033 -1.05454464
  1.13268034 -2.02664463  0.28209285 -1.29756964 -0.08244465 -0.56849464
 -1.54

In [6]:
df

0         1         2         3         4         5         6   \
0    0.160580  0.508950  0.057819  0.270806  1.307291  0.311542 -0.205844   
1   -0.325470 -0.626268  0.121261 -0.835244 -0.595396  0.094079 -0.597112   
2    1.254193  0.833298  1.517005  1.197496  0.546217  0.311542  1.148544   
3   -0.082445 -0.626268 -0.005624 -0.297166  0.165679  0.094079 -0.747600   
4   -1.054545 -0.139746 -0.766939  1.077923  5.239511  9.444962 -0.597112   
..        ...       ...       ...       ...       ...       ...       ...   
841 -0.082445 -0.950615  0.311590  0.420272  0.292525 -0.123383  0.004838   
842 -0.568495  0.184602  0.121261 -0.177593  0.546217  0.529004 -0.296137   
843  1.497218  1.481994  1.199790  1.586108  0.673062  0.746467  1.600007   
844 -0.933032 -1.437137 -0.259396 -0.685777 -0.468550 -0.340845 -1.018477   
845 -1.054545 -1.437137 -1.020711 -1.373322 -0.849087 -0.775770 -1.469940   

           7         8         9         10        11        12        13  \
0    0.136570 -0.224944  0.758332 -0.402383 -0.344935  0.285812 -0.329056   
1    0.520843 -0.610954 -0.344578 -0.593611 -0.622416 -0.513517 -0.061767   
2   -1.144341  0.933086  0.689401  1.095564  1.104766  1.392577  0.071877   
3    0.648935 -0.610954 -0.344578 -0.912323 -0.741337 -1.466565 -1.264566   
4    0.520843 -0.610954 -0.275646  1.669245 -0.650731  0.408786  7.288670   
..        ...       ...       ...       ...       ...       ...       ...   
841 -0.119612 -0.224944 -0.964965  0.362526 -0.101430 -0.790209 -0.061767   
842  0.264661 -0.224944  0.758332 -0.497997 -0.407226  0.039865 -0.061767   
843 -1.400524  1.705106  1.723379  1.254920  1.591775  0.777708 -0.329056   
844  1.161299 -0.996965 -1.654284 -1.071679 -0.962190 -0.820952 -0.863633   
845  1.929846 -1.382975 -1.378557 -1.549747 -1.290638 -1.343591  0.071877   

           14        15        16        17     18  
0   -0.076711  0.380991 -0.313722  0.183957   van   
1    0.533610  0.156925  0.010937  0.452977   van   
2    1.550812 -0.403238 -0.151393  0.049447   saab  
3   -0.076711 -0.291206  1.634233  1.529056   van   
4    0.533610 -0.179173 -1.450029 -1.699181   bus   
..        ...       ...       ...       ...    ...  
841  0.126729  1.389286 -0.151393 -0.085062   saab  
842 -1.093913  0.829122 -0.476052  0.183957   van   
843 -0.687032 -0.963402 -0.313722  0.721997   saab  
844 -1.297353  1.389286  0.173267 -0.085062   saab  
845 -1.093913  0.605056 -0.476052 -0.757612   van   

[846 rows x 19 columns]

In [7]:
last_column = df[df.columns[-1]]
value_counts = last_column.value_counts()
print(value_counts)

18
bus     218
saab    217
opel    212
van     199
Name: count, dtype: int64


In [8]:
train,val = train_test_split(df,test_size=0.2,random_state=4)

In [9]:

process_file_path = 'data//now//'+file_name
if not os.path.exists(process_file_path):
    os.makedirs(process_file_path)

In [10]:
train_file = os.path.join(process_file_path,'train.csv')
val_file = os.path.join(process_file_path,'val.csv')

In [11]:
train.to_csv(train_file)
val.to_csv(val_file)

In [25]:
val.shape

(3804, 11)

In [33]:
import torch

In [34]:
a=torch.rand((32,31))
b=torch.rand((32,3))

In [35]:
a

tensor([[0.9707, 0.0764, 0.4245, 0.7085, 0.2216, 0.8530, 0.7283, 0.4062, 0.5446,
         0.1030, 0.3580, 0.1232, 0.4551, 0.5578, 0.2180, 0.4257, 0.8176, 0.2824,
         0.8549, 0.9711, 0.6613, 0.2994, 0.9898, 0.8607, 0.8590, 0.8838, 0.4291,
         0.6770, 0.3870, 0.4120, 0.0997],
        [0.6529, 0.6566, 0.6432, 0.0077, 0.6433, 0.3695, 0.9142, 0.0824, 0.6309,
         0.1117, 0.6678, 0.3241, 0.1619, 0.5698, 0.3286, 0.4410, 0.9538, 0.1772,
         0.0359, 0.1520, 0.8728, 0.3762, 0.4204, 0.8435, 0.3092, 0.0570, 0.9595,
         0.7178, 0.7399, 0.7037, 0.3390],
        [0.1493, 0.0493, 0.6158, 0.7239, 0.7572, 0.4001, 0.1692, 0.3427, 0.5548,
         0.2804, 0.6053, 0.5224, 0.8443, 0.1576, 0.4028, 0.4913, 0.7254, 0.7044,
         0.3978, 0.7395, 0.8049, 0.0914, 0.6558, 0.6908, 0.7562, 0.0501, 0.2877,
         0.5118, 0.2641, 0.1336, 0.1724],
        [0.1435, 0.8594, 0.4401, 0.5083, 0.8357, 0.3723, 0.5191, 0.3237, 0.8756,
         0.8602, 0.6141, 0.8789, 0.0347, 0.9011, 0.7834, 0.3678,

In [36]:
b

tensor([[0.1998, 0.9022, 0.0109],
        [0.3817, 0.5112, 0.5241],
        [0.9575, 0.5575, 0.2820],
        [0.2198, 0.8832, 0.4810],
        [0.5276, 0.2002, 0.4732],
        [0.7494, 0.1911, 0.6328],
        [0.2328, 0.5689, 0.7737],
        [0.3366, 0.4341, 0.5599],
        [0.6424, 0.7483, 0.2894],
        [0.1907, 0.5157, 0.9835],
        [0.4854, 0.3847, 0.3751],
        [0.8109, 0.0983, 0.4619],
        [0.2901, 0.7925, 0.6697],
        [0.8102, 0.5963, 0.1189],
        [0.7075, 0.1135, 0.4009],
        [0.7234, 0.9708, 0.3696],
        [0.4633, 0.6601, 0.0516],
        [0.0508, 0.3206, 0.7963],
        [0.4725, 0.3088, 0.6692],
        [0.1127, 0.9854, 0.9227],
        [0.0737, 0.7030, 0.1356],
        [0.3010, 0.9824, 0.9558],
        [0.4190, 0.5209, 0.6255],
        [0.6538, 0.6511, 0.6351],
        [0.4106, 0.5597, 0.7147],
        [0.8339, 0.4618, 0.7290],
        [0.4448, 0.5814, 0.0789],
        [0.9752, 0.0691, 0.9519],
        [0.4021, 0.0251, 0.1269],
        [0.618

In [37]:
torch.cat([a,b],dim=-1)

tensor([[0.9707, 0.0764, 0.4245,  ..., 0.1998, 0.9022, 0.0109],
        [0.6529, 0.6566, 0.6432,  ..., 0.3817, 0.5112, 0.5241],
        [0.1493, 0.0493, 0.6158,  ..., 0.9575, 0.5575, 0.2820],
        ...,
        [0.4986, 0.8336, 0.0635,  ..., 0.6187, 0.9015, 0.0090],
        [0.9049, 0.8162, 0.1084,  ..., 0.0366, 0.9114, 0.9467],
        [0.6507, 0.4694, 0.1644,  ..., 0.3932, 0.2892, 0.7007]])

In [2]:
import torch
from torcheval.metrics import MulticlassAUROC
metric = MulticlassAUROC(num_classes=4)
input = torch.tensor([[0.1, 0.1, 0.1, 0.1], [0.5, 0.5, 0.5, 0.5], [0.7, 0.7, 0.7, 0.7], [0.8, 0.8, 0.8, 0.8]])
target = torch.tensor([0, 1, 2, 3])
metric.update(input, target)
metric.compute()

tensor(0.5000)